name: Update Calendar

on:
  schedule:
    - cron: "0 3 * * *" # every day at 03:00 UTC
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install node-fetch@2 cheerio ics

      - name: Run scraper
        run: node scrape.js

      - name: Commit calendar
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add calendar.ics
          git commit -m "Update calendar" || echo "No changes"
          git push
